### ISSUE TITLE
PA Review: Projects

### ISSUE THREAD

**Issue by michael-berman** [michael-berman/Blue-Prints#3]
Backend: DB, model, controller, views
-[] Redux Loop: ajax, actions, reducer
-[] Presentational Components
-[] Styling
-[] Smooth, bug-free navigation
-[] Adequate and appropriate seeds

**Comment by OscarAlvarez8830** [comment]
Creating a project without a title fails silently.

**Comment by OscarAlvarez8830** [comment]
Should I be able to create a project without any steps?

**Comment by michael-berman** [comment]
I have it set up so that there are errors for the blank title now, and that one step is fully complete. I have a default image set up so that when a user doesn't have a cover image, there's a default image that is set up in the database. Steps don't need to have images though but there must be at least one complete step before publishing meaning a title, body and images
